### ISSUE TITLE
Oregon shape cut on some resolutions

### ISSUE THREAD

**Issue by theMadness** [PHPDX/cascadiaphp.com#14]
Currently happening at 1246:707

**Comment by KorvinSzanto** [comment]
It looks like this happens at any standard `4x3` size < `1920x1080`. The reason is because the oregon shape is disregarding the parent size and instead following the `widths=` directive that tells it the size to be. This will need to be a bit untangled to work properly. Positioning this SVG properly takes a little bit of finesse.

**Comment by theMadness** [comment]
Fair.

**Comment by KorvinSzanto** [comment]
#20 fixed this
